### ISSUE TITLE
Defence

### ISSUE THREAD

**Issue by PopeCorn** [PopeCorn/card_game#5]
Několik variant jak by mohla fungovat defence:

**1. Od každého přicházejícího útoku odebere určitý počet bodů.** Příklad: 
Defence = 2, P. Útok = 4, HP = 5
- V tom případě budou obrána jen 2hp.

Klady - jednoduchost, srozumitelnost

Zápory - budeme muset předělat všechny _attack_, _defence_, _hp_ hodnoty, aby hra byla vybalanxovaná.

**2. Počítá se jako hp navíc.** Příklad:
Defence = 1, P. Útok = 4, HP = 5
- V tomto případě obránci zbyde 2 HP. 

Klady - extrémně ez, nemusíme téměř šahat do momentálního kódu.

Zápory - museli bychom pak ještě nějak s tou defence pracovat, např. ve speciálních abilitách; jinak jí totiž prostě můžeme ze hry vymazat a všem dát víc HP.

**Comment by PopeCorn** [comment]
Já jsem za 2. variantu s tím, že bych každému přidal ještě jednu speciální akci, u někoho např. healing apod. a u jiných např. právě třeba doplňování defence apod.

@marekececek25 prosím o vyjádření.

**Comment by PopeCorn** [comment]
Solved - defence je navrch hp

**Comment by marekececek25** [comment]
Hele Pavle možná se k tomu dnes nakonec dostanu a pokud ne tak se o to
pokusím zítra.

Dne út 20. 12. 2022 22:09 uživatel PopeCorn ***@***.***>
napsal:
